name: wheels

on:
  pull_request:
    paths:
      - "packaging/compute_wheel_version.sh"
      - ".github/workflows/wheel*"
      - "setup.py"
      - "requirements*.txt"
  push:
    branches:
      - main
    tags:
      - "v[0-9]+*"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          # Set corresponding CUDA version
          - torch_version: "2.0.1"
            cuda_short_version: "118"
            publish: false
            arch_list: "5.0+PTX 6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6 8.9 9.0"

          # - torch_version: "1.13.1"
          #   cuda_short_version: "117"
          #   publish: false
          #   arch_list: "5.0+PTX 6.0 6.1 6.2 7.0 7.2 7.5 8.0 8.6"

    uses: ./.github/workflows/wheels_reusable.yml
    if: github.repository == 'facebookresearch/xformers' || github.event_name == 'pull_request'
    with:
      os: ubuntu-22.04
      python: "3.10"
      torch_version: ${{ matrix.torch_version }}
      cuda_short_version: ${{ matrix.cuda_short_version }}
      publish: ${{ matrix.publish == true && github.event_name != 'pull_request'}}
      sdist: ${{ matrix.sdist == true }}
      arch_list: ${{ matrix.arch_list }}
      twine_username: __token__
    secrets:
      twine_password: ${{ secrets.PYPI_TOKEN }}
